taipeion-endpoint: https://tpgimtest.gov.taipei/API/MessageFeedService.ashx
channels:
  1: # Your channel ID.
    channel-secret: your-channel-secret
    channel-access-token: your-channel-access-token
address: 0.0.0.0
port: 443